// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzukYedpOvOEMMvsqXHCN_ljkuG74Ps_4',
    appId: '1:583740498854:web:18b6bfdaf689267d776567',
    messagingSenderId: '583740498854',
    projectId: 'twitter-clone-babd7',
    authDomain: 'twitter-clone-babd7.firebaseapp.com',
    storageBucket: 'twitter-clone-babd7.appspot.com',
    measurementId: 'G-T9JZME6SMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPeLFg63jWUKDgV6vLYf7CFVJh0uIYgIY',
    appId: '1:583740498854:android:b747bee28fc84a1d776567',
    messagingSenderId: '583740498854',
    projectId: 'twitter-clone-babd7',
    storageBucket: 'twitter-clone-babd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoYIjVUqijFwC7WVHLSpyjWQSWr3-AV-4',
    appId: '1:583740498854:ios:83e80694ca5e6780776567',
    messagingSenderId: '583740498854',
    projectId: 'twitter-clone-babd7',
    storageBucket: 'twitter-clone-babd7.appspot.com',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoYIjVUqijFwC7WVHLSpyjWQSWr3-AV-4',
    appId: '1:583740498854:ios:83e80694ca5e6780776567',
    messagingSenderId: '583740498854',
    projectId: 'twitter-clone-babd7',
    storageBucket: 'twitter-clone-babd7.appspot.com',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzukYedpOvOEMMvsqXHCN_ljkuG74Ps_4',
    appId: '1:583740498854:web:4ccb6bd011061d48776567',
    messagingSenderId: '583740498854',
    projectId: 'twitter-clone-babd7',
    authDomain: 'twitter-clone-babd7.firebaseapp.com',
    storageBucket: 'twitter-clone-babd7.appspot.com',
    measurementId: 'G-VV27EQDB8T',
  );

}